// Self-contained data URI placeholder avatar (no external asset file needed).
const avatar =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40' viewBox='0 0 40 40'%3E%3Ccircle cx='20' cy='20' r='20' fill='%23D9EEFF'/%3E%3Ctext x='20' y='25' text-anchor='middle' font-family='Arial, sans-serif' font-size='14' font-weight='600' fill='%230076B8'%3EEP%3C/text%3E%3C/svg%3E";

export const mockData = [
  {
    ticket: "test-2",
    scanType: "Network Scan",
    scanner: "Nessus",
    createdDate: "9/18/16",
    scanEndDate: "9/18/16",
    status: "New",
    cvss: { score: 1.4, level: "Low" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-2",
    scanType: "Web Scan",
    scanner: "OWASP ZAP",
    createdDate: "9/4/12",
    scanEndDate: "9/4/12",
    status: "New",
    cvss: { score: 4.6, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-2",
    scanType: "API Scan",
    scanner: "API Scan",
    createdDate: "5/27/15",
    scanEndDate: "5/27/15",
    status: "New",
    cvss: { score: 6.7, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-2",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "7/11/19",
    scanEndDate: "7/11/19",
    status: "New",
    cvss: { score: 8.5, level: "High" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-2",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "1/31/14",
    scanEndDate: "1/31/14",
    status: "New",
    cvss: { score: 9.6, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-2",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "10/28/12",
    scanEndDate: "10/28/12",
    status: "New",
    cvss: { score: 9.9, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-2",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "7/27/13",
    scanEndDate: "7/27/13",
    status: "New",
    cvss: { score: 9.1, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-2",
    scanType: "Web Scan",
    scanner: "Burp Suite",
    createdDate: "8/21/15",
    scanEndDate: "8/21/15",
    status: "New",
    cvss: { score: 9.3, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-2",
    scanType: "Web Scan",
    scanner: "Nikto",
    createdDate: "4/4/18",
    scanEndDate: "4/4/18",
    status: "New",
    cvss: { score: 9.8, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-2",
    scanType: "Web Scan",
    scanner: "Web Scan",
    createdDate: "3/4/16",
    scanEndDate: "3/4/16",
    status: "New",
    cvss: { score: 9.8, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-7",
    scanType: "Network Scan",
    scanner: "Nessus",
    createdDate: "9/18/16",
    scanEndDate: "9/18/16",
    status: "New",
    cvss: { score: 1.4, level: "Low" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-7",
    scanType: "Web Scan",
    scanner: "OWASP ZAP",
    createdDate: "9/4/12",
    scanEndDate: "9/4/12",
    status: "New",
    cvss: { score: 4.6, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-7",
    scanType: "API Scan",
    scanner: "API Scan",
    createdDate: "5/27/15",
    scanEndDate: "5/27/15",
    status: "New",
    cvss: { score: 6.7, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-7",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "7/11/19",
    scanEndDate: "7/11/19",
    status: "New",
    cvss: { score: 8.5, level: "High" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-7",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "1/31/14",
    scanEndDate: "1/31/14",
    status: "New",
    cvss: { score: 9.6, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "test-7",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "10/28/12",
    scanEndDate: "10/28/12",
    status: "New",
    cvss: { score: 9.9, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-7",
    scanType: "Source Code Review",
    scanner: "Qualys",
    createdDate: "7/27/13",
    scanEndDate: "7/27/13",
    status: "New",
    cvss: { score: 9.1, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-7",
    scanType: "Web Scan",
    scanner: "Burp Suite",
    createdDate: "8/21/15",
    scanEndDate: "8/21/15",
    status: "New",
    cvss: { score: 9.3, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-7",
    scanType: "Web Scan",
    scanner: "Nikto",
    createdDate: "4/4/18",
    scanEndDate: "4/4/18",
    status: "New",
    cvss: { score: 9.8, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Test-7",
    scanType: "Web Scan",
    scanner: "Web Scan",
    createdDate: "3/4/16",
    scanEndDate: "3/4/16",
    status: "New",
    cvss: { score: 9.8, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
];
