// Defensive-flavored counterpart to mockData.ts — same row shape (the
// DataTable/columns are generic), different values so the table reads as
// detection/response alerts instead of offensive vuln-scan findings.
const avatar =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40' viewBox='0 0 40 40'%3E%3Ccircle cx='20' cy='20' r='20' fill='%23D9EEFF'/%3E%3Ctext x='20' y='25' text-anchor='middle' font-family='Arial, sans-serif' font-size='14' font-weight='600' fill='%230076B8'%3EEP%3C/text%3E%3C/svg%3E";

export const mockDataDefensive = [
  {
    ticket: "alert-14",
    scanType: "Network Alert",
    scanner: "Splunk",
    createdDate: "9/18/16",
    scanEndDate: "9/19/16",
    status: "New",
    cvss: { score: 2.1, level: "Low" },
    assignee: { name: "Eleanor Pena", tier: "Tier 1", avatar },
  },
  {
    ticket: "Alert-14",
    scanType: "Endpoint Alert",
    scanner: "CrowdStrike",
    createdDate: "9/4/12",
    scanEndDate: "9/4/12",
    status: "New",
    cvss: { score: 5.2, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 2", avatar },
  },
  {
    ticket: "alert-14",
    scanType: "Identity Alert",
    scanner: "Okta ITDR",
    createdDate: "5/27/15",
    scanEndDate: "5/28/15",
    status: "New",
    cvss: { score: 6.4, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 2", avatar },
  },
  {
    ticket: "alert-14",
    scanType: "Insider Threat",
    scanner: "Datadog",
    createdDate: "7/11/19",
    scanEndDate: "7/11/19",
    status: "New",
    cvss: { score: 8.2, level: "High" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "alert-14",
    scanType: "Cloud Alert",
    scanner: "SentinelOne",
    createdDate: "1/31/14",
    scanEndDate: "1/31/14",
    status: "New",
    cvss: { score: 9.4, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "alert-14",
    scanType: "Endpoint Alert",
    scanner: "Microsoft Defender",
    createdDate: "10/28/12",
    scanEndDate: "10/28/12",
    status: "New",
    cvss: { score: 9.7, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-14",
    scanType: "Network Alert",
    scanner: "Splunk",
    createdDate: "7/27/13",
    scanEndDate: "7/27/13",
    status: "New",
    cvss: { score: 9.0, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-14",
    scanType: "Identity Alert",
    scanner: "Okta ITDR",
    createdDate: "8/21/15",
    scanEndDate: "8/21/15",
    status: "New",
    cvss: { score: 9.2, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-14",
    scanType: "Insider Threat",
    scanner: "Datadog",
    createdDate: "4/4/18",
    scanEndDate: "4/4/18",
    status: "New",
    cvss: { score: 9.6, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-14",
    scanType: "Cloud Alert",
    scanner: "SentinelOne",
    createdDate: "3/4/16",
    scanEndDate: "3/4/16",
    status: "New",
    cvss: { score: 9.5, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "alert-19",
    scanType: "Network Alert",
    scanner: "Splunk",
    createdDate: "9/18/16",
    scanEndDate: "9/18/16",
    status: "New",
    cvss: { score: 1.9, level: "Low" },
    assignee: { name: "Eleanor Pena", tier: "Tier 1", avatar },
  },
  {
    ticket: "Alert-19",
    scanType: "Endpoint Alert",
    scanner: "CrowdStrike",
    createdDate: "9/4/12",
    scanEndDate: "9/4/12",
    status: "New",
    cvss: { score: 4.3, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 2", avatar },
  },
  {
    ticket: "alert-19",
    scanType: "Identity Alert",
    scanner: "Okta ITDR",
    createdDate: "5/27/15",
    scanEndDate: "5/27/15",
    status: "New",
    cvss: { score: 6.1, level: "Medium" },
    assignee: { name: "Eleanor Pena", tier: "Tier 2", avatar },
  },
  {
    ticket: "alert-19",
    scanType: "Cloud Alert",
    scanner: "SentinelOne",
    createdDate: "7/11/19",
    scanEndDate: "7/11/19",
    status: "New",
    cvss: { score: 8.0, level: "High" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "alert-19",
    scanType: "Insider Threat",
    scanner: "Datadog",
    createdDate: "1/31/14",
    scanEndDate: "1/31/14",
    status: "New",
    cvss: { score: 9.3, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "alert-19",
    scanType: "Network Alert",
    scanner: "Splunk",
    createdDate: "10/28/12",
    scanEndDate: "10/28/12",
    status: "New",
    cvss: { score: 9.8, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-19",
    scanType: "Endpoint Alert",
    scanner: "Microsoft Defender",
    createdDate: "7/27/13",
    scanEndDate: "7/27/13",
    status: "New",
    cvss: { score: 9.1, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-19",
    scanType: "Cloud Alert",
    scanner: "SentinelOne",
    createdDate: "8/21/15",
    scanEndDate: "8/21/15",
    status: "New",
    cvss: { score: 9.4, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-19",
    scanType: "Identity Alert",
    scanner: "Okta ITDR",
    createdDate: "4/4/18",
    scanEndDate: "4/4/18",
    status: "New",
    cvss: { score: 9.7, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
  {
    ticket: "Alert-19",
    scanType: "Insider Threat",
    scanner: "Datadog",
    createdDate: "3/4/16",
    scanEndDate: "3/4/16",
    status: "New",
    cvss: { score: 9.9, level: "Critical" },
    assignee: { name: "Eleanor Pena", tier: "Tier 3", avatar },
  },
];
