import type { KanbanColumn } from "./components/Kanban/kanbanTypes";

export const mockKanbanData: KanbanColumn[] = [
  {
    id: "new",
    title: "New",
    tasksCount: 3,
    tasks: [
      {
        ticket_id: "T-101",
        name: "Add dark mode support",
        severity: "high",
        priority: "medium",
        assignees: [{ name: "Alice Cole" }],
        notes_count: 2,
        attachments_count: 1,
        comments_count: 3,
      },
      {
        ticket_id: "T-102",
        name: "Fix login button unclickable on iOS",
        severity: "medium",
        priority: "low",
        assignees: [{ name: "Bob Hart" }],
        notes_count: 1,
        attachments_count: 0,
        comments_count: 5,
      },
      {
        ticket_id: "T-103",
        name: "Customer data import feature",
        severity: "low",
        priority: "low",
        assignees: [{ name: "Charlie Wu" }],
        notes_count: 3,
        attachments_count: 2,
        comments_count: 0,
      },
    ],
  },
  {
    id: "in-progress",
    title: "In Progress",
    tasksCount: 2,
    tasks: [
      {
        ticket_id: "T-104",
        name: "Optimize API response time",
        severity: "critical",
        priority: "high",
        assignees: [{ name: "Alice Cole" }],
        notes_count: 4,
        attachments_count: 1,
        comments_count: 8,
      },
      {
        ticket_id: "T-105",
        name: "Redesign user settings page",
        severity: "medium",
        priority: "low",
        assignees: [{ name: "Bob Hart" }],
        notes_count: 0,
        attachments_count: 0,
        comments_count: 2,
      },
    ],
  },
  {
    id: "escalated",
    title: "Escalated",
    tasksCount: 1,
    tasks: [
      {
        ticket_id: "T-106",
        name: "Payment gateway timeout issue",
        severity: "critical",
        priority: "high",
        assignees: [{ name: "Charlie Wu" }],
        notes_count: 5,
        attachments_count: 2,
        comments_count: 6,
      },
    ],
  },
  {
    id: "resolved",
    title: "Resolved",
    tasksCount: 2,
    tasks: [
      {
        ticket_id: "T-107",
        name: "Update password strength policy",
        severity: "low",
        priority: "low",
        assignees: [{ name: "Alice Cole" }],
        notes_count: 1,
        attachments_count: 0,
        comments_count: 1,
      },
      {
        ticket_id: "T-108",
        name: "Fix email verification flow",
        severity: "high",
        priority: "medium",
        assignees: [{ name: "Bob Hart" }],
        notes_count: 2,
        attachments_count: 1,
        comments_count: 4,
      },
    ],
  },
  {
    id: "closed",
    title: "Closed",
    tasksCount: 1,
    tasks: [
      {
        ticket_id: "T-109",
        name: "User activity report enhancement",
        severity: "medium",
        priority: "low",
        assignees: [{ name: "Charlie Wu" }],
        notes_count: 1,
        attachments_count: 1,
        comments_count: 0,
      },
    ],
  },
];
